### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by asheenlevrai** [lupo49/plugin-enforcesummary#12]
Hi :)

I am currently running Greebo and considering upgrading to Hogfather.
This plugin is not compatible with Hogfather according to
https://www.dokuwiki.org/plugin:enforcesummary

Is it still maintained?

Thanks
-a-

**Comment by asheenlevrai** [comment]
It seems like it works on Hogfather.
However, I didn't test extensively

**Comment by asheenlevrai** [comment]
> This plugin is not really maintained but if somebody provides a pull request that looks good I can merge it. I might not always notice them, though, and sometimes I also just don't have time.

Thanks a lot. I understand that you may have other priorities.
Now, I'm not familiar with how all of this work, but if you merge pull requests, does that mean that eventually a new release would be available?

Best,
-a-

**Comment by michitux** [comment]
You can just re-install the plugin (there is a button for it in the extension manager) and you'll have the new version. I'll see if I can find the time to also actually release a new version but the download already points to the current version with all changes included.

**Comment by michitux** [comment]
As I have the [versionfix](https://github.com/splitbrain/dokuwiki-versionfix/) tool already configured, I've just released a new version. It should be up, feel free to open an issue if there should be any problem.

**Comment by asheenlevrai** [comment]
Thank you so much :)
